# Generated by Django 4.0.5 on 2022-06-27 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=50)),
                ('agents_quantity', models.IntegerField(default=0)),
                ('agents_memory', models.IntegerField(default=1)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_running', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.application')),
                ('cloud_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cloudprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=50)),
                ('cpu_usage', models.FloatField(default=0)),
                ('ram_usage', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
        ),
    ]
