# Generated by Django 4.0.5 on 2022-09-20 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='user',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OnQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='creating', max_length=20)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusters.cluster')),
            ],
        ),
    ]
