# Generated by Django 4.0.5 on 2022-06-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
