# Generated by Django 4.0.5 on 2022-09-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0004_cluster_app_url_alter_cluster_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='app_url',
            field=models.CharField(default='http://127.0.0.1:8080/ui', max_length=200),
        ),
    ]
